name: GitHub Actions Demo
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - stage
  pull_request:
jobs:
  Pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip' # caching pip dependencies
      - name: Install project
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pippip install -e .[dev]
      - name: Test with pytest
        run: |
          pytest

