name: Code validation on Pull Requests
on:
  workflow_dispatch:
  pull_request:
jobs:
  Pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Test with pytest
        run: |
          pytest

